### PR TITLE
feat: statistics (insights)

### PR DESCRIPTION
**Pull request by leMaur**
## Summary
https://app.clickup.com/t/jd88fa

This PR is related to **insights**.

image

## How To Test
1. in `.env` file, change Explorer Network to production `EXPLORER_NETWORK=production`
1. run `composer play`
1. run `php artisan explorer:cache-development-data` (this can take a moment)
1. run `php artisan explorer:cache-transactions`

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Review by ItsANameToo — CHANGES_REQUESTED** [review]

**Review by alfonsobries — CHANGES_REQUESTED** [review]
left some comments

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
- average fee should show fee options to switch between (transfer, 2nd sig, etc) and not a period like it does now
image

- as shown above, the max fee ends up being pushed on a second line. There seems to be too much padding used between the min/max values

- selecting `day` results in no chart
image

- when selecting the dropdown and clicking an option, it leaves it focused resulting in a visible ring 
image

- switching between timeframes takes a bit of time, we should add a loading indicator of some sorts. Ask Oleg/Rok about this

- can we use the rich select for the dropdowns? right now they make use of the native `select` element and we don't use that anywhere else

- what timeframe is used when a `year` is selected? Are the plots monthly or smaller?

- it might be better to have a job in the background that aggregates all the data that we show here, as opposed to creating it when the page is being asked for (it's slow to load at the moment). There is an existing job to aggregate fees that was used for the chart that used to be on the homepage, maybe something similar to that can be created for the current statistics page

**Review by ItsANameToo — COMMENTED** [review]
- for responsiveness, the charts should have less space between them

design:
image

implementation:
image

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
- you'll need some axis padding to ensure the lines don't get cut off. Compare with the homepage statistics chart where there is a small (iirc 1%) value added to the max and min values to avoid it cutting off.
image

- fees shouldn't show `all`, only the actual transaction types and the associated fees
image

- larger fees take 2 lines and mess with the alignment of the boxes
image

- the `all` value is 0 for all boxes. Day/week/etc show fine but `all` results in 0
image

image

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
have an errant to run, will continue the review after that

**Review by ItsANameToo — CHANGES_REQUESTED** [review]

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
almost there, a few remarks left:
image

- can you change the truncation to only be 3 decimals when it's >= 10000 instead of applying it to all values? It results in confusing values (e.g. 123.456 as that can be read as 123 or 123k) and in unused space when values are shown as 0.933
- can you check on what's up with the min/max fee spacing? it doesn't look like it equally divides the available space, making the max fee end up on two lines

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
