### PR TITLE
feat: add wallet uri prefix to the env settings

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

https://app.clickup.com/t/yy9nx1

Now the wallet prefix is set through the `.env` file

Since payvo will be the main app I am using that as default so ensure to set `WALLET_PREFIX=ark` setting on production and development server before merging this PR

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by alexbarnsley — CHANGES_REQUESTED** [review]
Works well other than my 1 comment. I omitted the colon and did `WALLET_PREFIX=blabla` which resulted in `blablaDABvMxuZvgd5JhseLATv1hAFfbioyCEBs5`, where the browser interpreted it as: http://test-explorer.test/wallets/blablaDABvMxuZvgd5JhseLATv1hAFfbioyCEBs5

**Comment by alfonsobries** [comment]
@alexbarnsley ✅

**Review by alexbarnsley — APPROVED** [review]
I'm happy with that! I'm not sure if we need to user-proof it (e.g. prevent special characters) since that would be part of the setup. I'll approve and let @ItsANameToo decide if it needs that or not :oleglala:

**Comment by ItsANameToo** [comment]
like this is fine with me

**Comment by ItsANameToo** [comment]
@alfonsobries I renamed the var to `EXPLORER_URI_PREFIX` to make it more explicit where it is used

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
