### PR TITLE
feat: custom 404 page for transactions/wallets and blocks

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

This PR solves two issues (needed to make a single PR since changes are correlated)

1. https://app.clickup.com/t/jd8cyb (custom 404 pages)
2. https://app.clickup.com/t/jvb1qw (broken theme switcher)

For the second ticket, the error is related to some csrf_token on 404 pages that broke livewire. Fixed the issue by redirecting 404 pages (except for the custom ones) to a custom view.  (This is the same solution we applied on marketsquare)

### To test

Open a page for an unexisting transaction and block
- https://explorer.ark.io.test/blocks/adfgadsg
- https://explorer.ark.io.test/transactions/xsdgdfghsdf

For the specific case of the wallets you should test:
1. A random wallet id string https://explorer.ark.io.test/wallets/random-string (should return a regular 404 page since is not a valid wallet)
2. A valid wallet that doesn't exist (you can grab one from the file `tests/fixtures/wallets.json`) this one should show the custom 404 page that says that doesn't exist yet

Test on different screen sizes  and in dark mode and light mode

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Functionality wise everything works as expected.

Is it possible to reduce some of the space here on the error pages though? 

image

**Review by samharperpittam — APPROVED** [review]

**Review by alexbarnsley — CHANGES_REQUESTED** [review]
requesting changes to highlight the above

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
- dark mode 404 (http://explorer.test/asdfasdf) shows light-mode image (this also applies to wallet page, e.g. http://explorer.test/wallets/FDCA2t34noDYiV9Xq835G2pPVMc5Fi4qjXa for a non-existing wallet)
image

- the urls get rewritten from http://explorer.test/asdfasdf to http://explorer.test/404?url=http%3A%2F%2Fexplorer.test%2Fasdfasdf , why's that? 🤔 

- blocks/tx/wallets look fine otherwise when the cat 404 shows

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
@alfonsobries this is now throwing error 500 when I try to access a wallet page that doesn't exist

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
