### PR TITLE
feat: transactions & block page design adjustments

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

https://app.clickup.com/t/k56uuu

Updates the icons used on the block and transaction details page and misc UI changes to match the current design

To test open different transaction types and compare them with the design https://www.figma.com/file/8ZexFq75tuiqqp1IAuFqJd/Explorer?node-id=2074%3A39

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Review by alexbarnsley — CHANGES_REQUESTED** [review]
@alfonsobries am i looking at the correct page on the figma design? i have gone through and picked out some of the wrong icons / differences when comparing the figma you linked with this branch (see below). I stopped checking so this may not be everything. Let me know if I'm looking at the wrong design please

# Transaction

## Timestamp

image

design:

image

## Fee

image

design:

image

## SmartBridge

image

design:

image

## Copy

image

design:

image

## MultiPayment

image

develop:

image

design: 

image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
On the Block Details page we can remove the duplicated "Reward" value identified by the `X` below
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
When viewing either a block details page or transaction page at 640 or 375, the icons within the grey box should be hidden.

**Design**
image


**Implementation**
 
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Multivote transaction details page is showing an incorrect delegate.

Look at the following URL
`/transactions/c2447262036853857cbc8f06f5d93496f9ca1b68bddf671ba9e33d12fc269cd3` 

On this PR it's showing that the multivote transaction unvoted and voted for "geops".

image


Though, when checking the same transaction on dexplorer [here ](https://dexplorer.ark.io/transactions/c2447262036853857cbc8f06f5d93496f9ca1b68bddf671ba9e33d12fc269cd3) you'll see that this transaction actually unvoted 'baldninja'. 

image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Multivote Transaction page is showing an additional divider.

**Design**
image


**Implementation**
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
- Multisig Reg transaction details - Move 'M-of-N' to the grid below.

**Design**
image


**Implementation**
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
- Multisig Reg Transaction Details - Participants should be a list.

**Design**
image

**Implementation**
image

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
@alfonsobries see also the remarks from sam in earlier comments

**Review by samharperpittam — CHANGES_REQUESTED** [review]
When viewing a Transaction or Block details page on breakpoint 768/640/375, we have lost padding between title and content within the grey box as illustrated below.

image

**Review by samharperpittam — APPROVED** [review]

**Review by alexbarnsley — CHANGES_REQUESTED** [review]
# Block page

**The wrong icon is used on the Block page for "Transaction Volume". It should match the "Amount" on the Transaction pages**

Design:
image

Implementation:
image

Transaction Page Implementation:
image

**[< 768px] Vertical spacing between transaction data is too small**

24px vs 16px may not be 100% accurate since implementation has padding up to the wallet avatar, whereas design has the avatar overlap slightly

Design (24px):
image
image

Implementation (16px):
image 
image

**[< 768px] Confirmations aren't shown for transactions**

Design:
image

Implementation:
image

**[>= 768px] Sections aren't quite centralised, or spacing between height, timestamp, etc is too small **
**Applies to Transaction page too**

Design:
image

image

Implementation:
image

image

image

**[768] arrows should be shown below Block ID**

Design:
image

Implementation:
image

# Transaction Page

**[768] icons should be visible**

Design:
image

Implementation:
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Sorry @alfonsobries  - Can we change 'Multisignature Registration' back to simply 'Multisignature' please?

Should fix these issues. 
image
image

**Review by samharperpittam — APPROVED** [review]

**Review by ItsANameToo — CHANGES_REQUESTED** [review]

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
