### PR TITLE
refactor: table ordering

### PR DESCRIPTION
**Pull request by Highjhacker**
## Summary

https://app.clickup.com/t/bgwe5b

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
also check the PR description, I updated it to be up to date with the changes and what's left

**Review by alfonsobries — CHANGES_REQUESTED** [review]
Other than my comments above, the backend part looks good. May need to check again once the latest dev changes are merged here.

**Comment by ItsANameToo** [comment]
at this point I'm more in favour of leaving this option and reimplementing it at a later time than continuing this branch 🤔 Main issue here is that we sort on the DB level while the existing explorer only sorts what is on the screen, so the behaviour will differ when this approach gets implemented and I'm still unsure how useful that way of sorting is to the average user.

Will reconsider this after the other PRs are merged and decide on what to do with it

**Comment by ItsANameToo** [comment]
Closing this due to it being heavily outdated and the sorting still needing changes to make it feel and work well. We may revisit this in the future but no concrete plans as of now

**Pull request closed without merging**
