### PR TITLE
refactor: delegates page information boxes design changes

### PR DESCRIPTION
**Pull request by Highjhacker**
## Summary

https://app.clickup.com/t/k13x5b

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Review by ItsANameToo — CHANGES_REQUESTED** [review]

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
- should the skeletons have a loading state like the tables have?
image

- can the skeletons be brought in line with the actual data that is shown afterwards?
image
image

- this section should be removed, see design
image

- the right-most icon has a wrong background color
image

- the right-most icon is not the same as used in the design
image

- in the design, this section is blue with a circle that gets filled when blocks are forged
image

- icon is not centered with the text
image

- on mobile, the horizontal scroll should have padding on the right side like it has on the left. Compare it with the statistics boxes on the homepage
image

**Review by alfonsobries — CHANGES_REQUESTED** [review]
Just the comments I added above

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
- current round icon is too small compared to the design
implementation
image

design
image

**Review by ItsANameToo — CHANGES_REQUESTED** [review]

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
- the circles are not centered with the "text" lines
image

- the loading state has a slightly different size, so when the actual data gets displayed it shifts the UI a little bit

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
