### PR TITLE
refactor: delegate wallet info boxes

### PR DESCRIPTION
**Pull request by Highjhacker**
## Summary

https://app.clickup.com/t/jd8b29

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — CHANGES_REQUESTED** [review]
The 'See All' links for Forged Blocks and Votes should be right aligned.

**Design**
image


**Implementation**
image

(Also the title text looks a different colour, should be using secondary-500, currently using secondary 700)

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Both Forged Blocks and Votes title should also be right aligned so 'Votes' is aligned with the QR code scan button

**Design**
image

**Implementation**
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
When an address has been resigned, the following needs changing

- The status icons should be grey (1)
- The `#0` Rank needs to be hidden (2)
- The 'Productivity' stat needs to be hidden (3)
- The total forged value changes to `secondary-500` 


**Design**
image

**Implementation**
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
The following issues apply to Active/Standby and Resigned

- The 2 circles should have a gap between them (1)
- The background of the second circle should be grey not white (2)
- The padding on the right of 'Votes' prevents it from aligning to the QR code button correctly (3). Is there a reason for it? 

**Design**
image

**Implementation**
image

And obviously the padding in general still needs work. Does it need to be done in a separate PR? :hmhm:

**Review by samharperpittam — CHANGES_REQUESTED** [review]
- 768 Breakpoint. 'Total Forged' touches the edge of the screen and padding needs reducing between titles to bring it closer to the design. 

**Design**
image

**Implementation**
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
- 375 Breakpoint - More padding required where marked on the image. Tis a bit compact currently. 

**Design**
image


**Implementation**
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Votes still not aligned with the QR code button. 
image

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
will recheck later today for more remarks, lunch first

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
- too much padding between the address and "voting for" section
image

- these titles should be gray-500 instead of gray-600
image

- padding of these components is not in line with the design & these titles should also be gray-500 instead of -600
image

- standby icon in dark mode should be darker (the `standby` text also looks like the wrong shade of gray)
image
design:
image

- please change productivity from `0.00%` to `N/A` until it's properly implemented.

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
- this seems to lack a bit of padding between the top and bottom row. Also the line doesn't seem to be the correct color in dark mode
image

- not sure if this is just your PR or not, but noticed that this is lacking padding 
image

- ~productivity color is not the same as the rest of the dark mode texts (compare with total forged value, it's lighter)~ ignore, it's standby and that apparently has a different color
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
- 768 & 640 - Bottom padding not aligned to 'See All' correctly.

image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
- Standby (dark mode). 'Standby' text should be `dark:text-theme-secondary-700` 
image

**Design**
image

Also there's no need to have a space between `#` and the number. 

`# 52` becomes `#52`

**Review by samharperpittam — CHANGES_REQUESTED** [review]
- Resigned (dark mode). 'Total Forged' value should be `dark:text-theme-secondary-700`

image

**Design**
image

**Review by samharperpittam — APPROVED** [review]

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
