### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by leMaur**
## Summary
https://app.clickup.com/t/12pgr17
depends on https://github.com/ArkEcosystem/laravel-ui/pull/662

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
- dropdowns have issues with the arrow
image
image

**Comment by ItsANameToo** [comment]
@leMaur still have the issue with the dropdowns. The workflow seems to recompile the assets as yours are different. Do you have any local changes that are not pushed or made to vendor files?

**Comment by leMaur** [comment]
> @leMaur still have the issue with the dropdowns. The workflow seems to recompile the assets as yours are different. Do you have any local changes that are not pushed or made to vendor files?

It seems linked to a change I did on UI. I'll double check...

**Comment by leMaur** [comment]
@ItsANameToo need to adjust rich-select on UI and now I'm able to adjust the margin to tweak the button.

image

**Comment by ItsANameToo** [comment]
@leMaur conflicts

**Comment by leMaur** [comment]
@ItsANameToo ✅ - I'll keep in draft until https://github.com/ArkEcosystem/laravel-ui/pull/662 will be merged.

**Pull request closed without merging**
